---
- name: Stop service httpd, if started
  service:
    name: httpd
    state: stopped

- name: Cleaning Up
  file:
    state: absent
    path: "{{ item }}"
  with_items:
      - "/var/www/eSchool"

- name: Create a directory if it does not exist
  file:
    path: /var/www/eSchool
    state: directory
    mode: '0755'

- name: Copy directory
  copy:
    src: /home/centos/eSchool/
    dest: /var/www/eSchool/
    owner: centos
    group: centos
    mode: '0777'

- name: Start service httpd, if not started
  service:
    name: httpd
    state: started
